### ISSUE TITLE
Auto-detection of languages for GitHub action workflow's `run:` blocks

### ISSUE THREAD

**Issue by kdeldycke** [harrydowning/yaml-embedded-languages#27]
Would it be a good idea to let this extension infer the language of a `run:` block from a GitHub action workflow based on its `shell:` directive?

The idea would be to have this block:
```yaml
(...)
jobs:

  my-job:
    steps:
      - name: My step
        shell: python
        run: |
          print("Hello world!")

(...)
```

to be rendered automatically by `yaml-embedded-languages` as if it was declared as:
```yaml
(...)
jobs:

  my-job:
    steps:
      - name: My step
        shell: python
        run: |  # python
          print("Hello world!")

(...)
```

This is also being discussed on `vscode-github-actions` at: https://github.com/github/vscode-github-actions/issues/266
