### ISSUE TITLE
Feature Request: Add support for syntax highlighting in Helm files

### ISSUE THREAD

**Issue by kahirokunn** [harrydowning/yaml-embedded-languages#66]
## Description
Currently, the YAML Embedded Languages extension provides excellent syntax highlighting for embedded code blocks within YAML and GitHub Actions Workflow files. I would like to request adding support for Helm files as well.

Helm is a popular package manager for Kubernetes that uses YAML-based templates. When working with Helm charts, it would be very helpful to have the same syntax highlighting capabilities for embedded code blocks that are currently available for regular YAML files.

## Use Case
When developing Helm charts, we often include various code snippets (like shell scripts, JSON, or other languages) within YAML block scalars. Having proper syntax highlighting for these embedded code blocks would significantly improve readability and reduce errors.

For example:
```yaml
# In a Helm template file (.yaml, .tpl, etc.)
data:
  script.sh: | # shell
    #!/bin/bash
    echo "This is a shell script embedded in a Helm file"
    if [ "$CONDITION" = "true" ]; then
      kubectl apply -f config.yaml
    fi
```

## Implementation Suggestion
Since Helm files are based on YAML, the implementation might be similar to how GitHub Actions Workflow support was added. This would involve:

1. Adding a new grammar definition file for Helm (similar to `source.yaml.injection.tmLanguage.json`)
2. Updating the extension to recognize Helm file extensions and language identifiers
3. Ensuring the same language embedding functionality works in Helm files

## Additional Information
- Helm files typically use extensions like `.yaml`, `.yml`, `.tpl`, or `.helm.yaml`
- The VS Code language identifier for Helm is typically `helm` or it might fall back to `yaml`

Thank you for considering this feature request!
